### ISSUE TITLE
Better link between API and Extension

### ISSUE THREAD

**Issue by mcorner** [w69b/castify-api-docs#12]
If you hit record in the extension and then try to start recording from js it says "busy", which is good.

But if you are recording from the extension and ask for the state it says inactive.  So it is not possible to tell if a user started recording with the button.

Similarly it isn't possible to add a payload to a recording started via the extension.

**Comment by Schibum** [comment]
That's intentional behaviour, the API only allows to control recordings that it started. 
I'll contact you offline to learn more about your use-case.
