### ISSUE TITLE
Error on Meteor

### ISSUE THREAD

**Issue by groblochon** [w69b/castify-api-docs#2]
Hi,

I added a screencastify plugins for Meteor (https://github.com/groblochon/meteor-screencastify) but an error occured on startup : 

```
Uncaught TypeError: Cannot read property 'registerModule' of undefined
(anonymous function) @ castify-api.js:3
```

Have you some idea ?

**Comment by Schibum** [comment]
Hi,
I just digged into it. castify-api.js currently bundles traceur-runtime, which assumes to be loaded globally (it writes to window.System and assumes that this can be accessed globally as System). Meteor, however auto-scopes global variables, effectively breaking traceur-runtime.

Loading castify-api.js in the outer scope like this should work:

```
var loader = document.createElement('script');
loader.src = "https://www.screencastify.com/libs-api/castify-api.js";
document.getElementsByTagName('head')[0].appendChild(loader);
```

I'll try to provide castify-api.js alternatively as an ES6 module in the future.

**Comment by Schibum** [comment]
Closing, please re-open If you should still experience this issue.
