### ISSUE TITLE
There is a typo in Screencastify.

### ISSUE THREAD

**Issue by ryanpcmcquen** [w69b/castify-api-docs#4]
I wasn't sure where else to contact anyone on this:

![screenshot-2015-11-08-at-18 57 57-compressor](https://cloud.githubusercontent.com/assets/772937/11025046/51ea1a32-864b-11e5-861f-490e97083cce.png)

There should be a space in between _are_ and _stored_.

Anyways, Screencastify is awesome, thanks!

**Comment by ryanpcmcquen** [comment]
Also another typo:

![screenshot-2015-11-08-at-19 05 11-compressor](https://cloud.githubusercontent.com/assets/772937/11025079/b88d13a2-864b-11e5-89b2-6ec67e0285f5.png)

Space needed between _is_ and _stored_.

**Comment by Schibum** [comment]
Thank you. Fixed in 1.11.2

**Comment by ryanpcmcquen** [comment]
Thank you! Screencastify is awesome!
