### ISSUE TITLE
Cannot read property 'closed' of undefined

### ISSUE THREAD

**Issue by jahirbsetec** [w69b/castify-api-docs#5]
@Schibum Hi, When I try to connect to the app using screencastify.connectApp() function I'm getting undefined error

castify-api.js:4 Uncaught TypeError: Cannot read property 'closed' of undefined

http://image.prntscr.com/image/2fa50294607b44a2bbced9330d60c4a8.png
http://image.prntscr.com/image/4cb9f3ea5026474e878e0ae5a81b7d3a.png

```
screencastify.setAppId('MY_APP_CODE');
screencastify.isAppConnected().then(function(isConnected) {
    if(isConnected){
        console.log('App is ' + (isConnected ? 'connected' : 'not connected'));
    } else {
        console.log('connectApp');
        screencastify.connectApp().then(function() {
          console.log('App is connected now');
          }, function(err) {
            console.error('failed to connect App', err);
        });
    }
});
```

**Comment by Schibum** [comment]
Hi,
connectApp() will only work when called from a user gesture event handler. It opens a window using window.open(), which will fail if not called in response to a click event or similar.
isAppConnected() is asynchronous, so your sample code wont work.
It would help if the API lib produced a more meaningful error message in this case though. I'll make sure to get it updated accordingly .

**Comment by jahirbsetec** [comment]
Hi, Thank you for the suggestion, I got it work using the click event

**Comment by jahirbsetec** [comment]
Hi @Schibum, I'm getting the file id in the shareURL, How can I store it into my recordings on chrome extension?

**Comment by Schibum** [comment]
Hi,
the API was designed for cases where storage is handled completely by the API user. So recordings initiated with the API don't appear in the "Your Recordings" view in Screencastify and there is currently no way to put them there. It could be extended accordingly though. What's your use-case for this? I'll get back to you directly to discuss.

**Comment by jahirbsetec** [comment]
Hi @Schibum, Thank you for your reply. My use-case is to view and store the video directly to YouTube Channel/Google Drive, which is same function what the extension does. I can access the file on my recordings page by changing the id(id from shareURL) on the URL (http://image.prntscr.com/image/8f4c27759fc44c6ab59678821e5fdec5.png), but if it is automated that would be great. Any suggestion would be greatly appreciated
